// Fetches every wiki page listed below and writes a structured
// report to ./scraped/reports/<slug>.json. This is the manual
// data source for the editor's machine catalog.
//
// Run with: node fetch-reports.mjs
//
// The "page" field in each report stores the raw wiki HTML for
// reference. The "data" field is the hand-extracted structured
// recipe / port / footprint data.

import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const PAGES = [
  // Logistics (8) — all are passthrough addons
  ["Belt_Bridge", "Belt Bridge", "Logistics Units", [1, 1], 0,
    "A logistics unit that lets 2 transport belts intersect without obstructing each other.", []],
  ["Converger", "Converger", "Logistics Units", [1, 1], 0,
    "Merges up to 3 transport belts into 1 single belt.", []],
  ["Item_Control_Port", "Item Control Port", "Logistics Units", [1, 1], 0,
    "Filters items; only the selected item passes through. Hard limit 1-5000.", []],
  ["Pipe_Bridge", "Pipe Bridge", "Logistics Units", [1, 1], 0,
    "Bridges 2 independent pipes so they can cross without obstruction.", []],
  ["Pipe_Control_Port", "Pipe Control Port", "Logistics Units", [1, 1], 0,
    "Filters fluids; only the selected fluid passes through. Hard limit 1-5000.", []],
  ["Pipe_Converger", "Pipe Converger", "Logistics Units", [1, 1], 0,
    "Merges up to 3 pipes into 1 single pipe.", []],
  ["Pipe_Splitter", "Pipe Splitter", "Logistics Units", [1, 1], 0,
    "Splits product flows from 1 pipe into up to 3 output pipes.", []],
  ["Splitter", "Splitter", "Logistics Units", [1, 1], 0,
    "Splits product flows from 1 belt into up to 3 output belts.", []],

  // Depot Access (9) — most are passthrough storage / transport
  ["Conduit_Inlet", "Conduit Inlet", "Depot Access", [5, 5], 0,
    "Item input port for connecting a Depot Bus to the AIC.", []],
  ["Conduit_Inlet_Manifold", "Conduit Inlet Manifold", "Depot Access", [5, 5], 0,
    "Manifold variant of the Conduit Inlet for multiple inputs.", []],
  ["Conduit_Outlet_Manifold", "Conduit Outlet Manifold", "Depot Access", [5, 5], 0,
    "Manifold variant of the Conduit Outlet for multiple outputs.", []],
  ["Depot_Bus_Port", "Depot Bus Port", "Depot Access", [5, 5], 0,
    "Item bus port for connecting a Depot Bus to a facility.", []],
  ["Depot_Bus_Section", "Depot Bus Section", "Depot Access", [5, 5], 0,
    "Section of a Depot Bus (storage).", []],
  ["Depot_Loader", "Depot Loader", "Depot Access", [5, 5], 0,
    "Loads items from a Depot Bus into an AIC facility.", []],
  ["Depot_Unloader", "Depot Unloader", "Depot Access", [5, 5], 0,
    "Unloads items from an AIC facility onto a Depot Bus.", []],
  ["Fluid_Tank", "Fluid Tank", "Depot Access", [5, 5], 0,
    "Stores fluids for the AIC.", []],
  ["Protocol_Stash", "Protocol Stash", "Depot Access", [5, 5], 0,
    "Stores items for the AIC.", []],

  // Production I (7)
  ["Fitting_Unit", "Fitting Unit", "Production I", [5, 5], 20,
    "A facility capable of processing various parts.", [
      { inputs: [{ resource: "Ferrium", kind: "item", rate: 30 }],
        outputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Amethyst Fiber", kind: "item", rate: 30 }],
        outputs: [{ resource: "Amethyst Part", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Steel", kind: "item", rate: 30 }],
        outputs: [{ resource: "Steel Part", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Cryston Fiber", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cryston Part", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Cuprium", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cuprium Part", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Hetonite", kind: "item", rate: 30 }],
        outputs: [{ resource: "Hetonite Part", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Pyrrolite", kind: "item", rate: 30 }],
        outputs: [{ resource: "Pyrrolite Part", kind: "item", rate: 6 }], time: 10 },
    ]],
  ["Moulding_Unit", "Moulding Unit", "Production I", [5, 5], 20,
    "A facility capable of processing various plates.", [
      { inputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Ferrium Plate", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Amethyst Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Amethyst Plate", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Steel Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Steel Plate", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Cuprium Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cuprium Plate", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Cryston Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cryston Plate", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Hetonite Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Hetonite Plate", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Xiranite Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Xiranite Plate", kind: "item", rate: 30 }], time: 2 },
    ]],
  ["Planting_Unit", "Planting Unit", "Production I", [5, 5], 20,
    "A facility for processing seeds into plants.", [
      { inputs: [{ resource: "Jincao Seed", kind: "item", rate: 30 }],
        outputs: [{ resource: "Jincao", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Yazhen Seed", kind: "item", rate: 30 }],
        outputs: [{ resource: "Yazhen", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Sandleaf Seed", kind: "item", rate: 30 }],
        outputs: [{ resource: "Sandleaf", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Buckflower Seed", kind: "item", rate: 30 }],
        outputs: [{ resource: "Buckflower", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Citrome Seed", kind: "item", rate: 30 }],
        outputs: [{ resource: "Citrome", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Aketine Seed", kind: "item", rate: 30 }],
        outputs: [{ resource: "Aketine", kind: "item", rate: 30 }], time: 2 },
    ]],
  ["Refining_Unit", "Refining Unit", "Production I", [5, 5], 5,
    "A facility that performs high temperature refining of various materials.", [
      { inputs: [{ resource: "Ferrium Ore", kind: "item", rate: 30 }],
        outputs: [{ resource: "Ferrium", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Ferrium Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Ferrium", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Amethyst Ore", kind: "item", rate: 30 }],
        outputs: [{ resource: "Amethyst Fiber", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Amethyst Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Amethyst Fiber", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Originium Ore", kind: "item", rate: 30 }],
        outputs: [{ resource: "Origocrust", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Origocrust Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Origocrust", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Dense Origocrust Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Packed Origocrust", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Dense Ferrium Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Steel", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Cryston Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cryston Fiber", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Dense Carbon Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Stabilized Carbon", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Dense Originium Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Dense Origocrust Powder", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Originium Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Origocrust Powder", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Yazhen", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon", kind: "item", rate: 60 }], time: 2 },
      { inputs: [{ resource: "Jincao", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon", kind: "item", rate: 60 }], time: 2 },
      { inputs: [{ resource: "Sandleaf", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Buckflower", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Citrome", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Wood", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Yazhen Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon Powder", kind: "item", rate: 60 }], time: 2 },
      { inputs: [{ resource: "Jincao Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon Powder", kind: "item", rate: 60 }], time: 2 },
      { inputs: [{ resource: "Sandleaf Powder", kind: "item", rate: 90 }],
        outputs: [{ resource: "Carbon Powder", kind: "item", rate: 60 }], time: 2 },
      { inputs: [{ resource: "Buckflower Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon Powder", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Citrome Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon Powder", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Ground Buckflower Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Dense Carbon Powder", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Ground Citrome Powder", kind: "item", rate: 30 }],
        outputs: [{ resource: "Dense Carbon Powder", kind: "item", rate: 30 }], time: 2 },
      // Fluid Mode
      { inputs: [{ resource: "Cuprium Ore", kind: "fluid", rate: 30 }, { resource: "Clean Water", kind: "fluid", rate: 30 }],
        outputs: [{ resource: "Cuprium", kind: "fluid", rate: 30 }, { resource: "Sewage", kind: "fluid", rate: 30 }], time: 2 },
    ]],
  ["Seed-Picking_Unit", "Seed-Picking Unit", "Production I", [5, 5], 20,
    "A facility for picking seeds and processing parts.", [
      { inputs: [{ resource: "Amethyst Fiber", kind: "item", rate: 30 }],
        outputs: [{ resource: "Amethyst Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Ferrium", kind: "item", rate: 30 }],
        outputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Steel", kind: "item", rate: 30 }],
        outputs: [{ resource: "Steel Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Cuprium", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cuprium Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Cryston Fiber", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cryston Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Hetonite", kind: "item", rate: 30 }],
        outputs: [{ resource: "Hetonite Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Wood", kind: "item", rate: 30 }],
        outputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Sandleaf", kind: "item", rate: 30 }],
        outputs: [{ resource: "Wood", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Wood", kind: "item", rate: 30 }],
        outputs: [{ resource: "Jincao Seed", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Wood", kind: "item", rate: 30 }],
        outputs: [{ resource: "Buckflower Seed", kind: "item", rate: 30 }] },
    ]],
  ["Shredding_Unit", "Shredding Unit", "Production I", [5, 5], 20,
    "A facility capable of grinding materials into powders.", [
      { inputs: [{ resource: "Cuprium", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cuprium Powder", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Ferrium", kind: "item", rate: 30 }],
        outputs: [{ resource: "Ferrium Powder", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Amethyst Fiber", kind: "item", rate: 30 }],
        outputs: [{ resource: "Amethyst Powder", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Originium Ore", kind: "item", rate: 30 }],
        outputs: [{ resource: "Originium Powder", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Carbon", kind: "item", rate: 30 }],
        outputs: [{ resource: "Carbon Powder", kind: "item", rate: 60 }], time: 2 },
      { inputs: [{ resource: "Steel", kind: "item", rate: 30 }],
        outputs: [{ resource: "Steel Powder", kind: "item", rate: 30 }], time: 2 },
      { inputs: [{ resource: "Yazhen", kind: "item", rate: 30 }],
        outputs: [{ resource: "Jincao", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Sandleaf", kind: "item", rate: 30 }],
        outputs: [{ resource: "Sandleaf Powder", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Buckflower", kind: "item", rate: 30 }],
        outputs: [{ resource: "Buckflower Powder", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Citrome", kind: "item", rate: 30 }],
        outputs: [{ resource: "Citrome Powder", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Wood", kind: "item", rate: 30 }],
        outputs: [{ resource: "Wood Chips", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Ferrium", kind: "item", rate: 30 }],
        outputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }] },
    ]],
  ["Water_Treatment_Unit", "Water Treatment Unit", "Production I", [5, 5], 0,
    "A facility that processes polluted water. Recipe details should be added by the user.", []],

  // Production II
  ["Expanded_Crucible", "Expanded Crucible", "Production II", [5, 5], 0,
    "A facility for processing bottles. Recipe details should be added by the user.", []],
  ["Filling_Unit", "Filling Unit", "Production II", [5, 5], 20,
    "A facility capable of filling containers with various materials.", []],
  ["Forge_of_the_Sky", "Forge of the Sky", "Production II", [5, 5], 0,
    "A facility for advanced smelting.", [
      { inputs: [{ resource: "Amethyst Part", kind: "item", rate: 60 }],
        outputs: [{ resource: "Amethyst Plate", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Ferrium Part", kind: "item", rate: 60 }],
        outputs: [{ resource: "Ferrium Plate", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Steel Part", kind: "item", rate: 60 }],
        outputs: [{ resource: "Steel Plate", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Cryston Part", kind: "item", rate: 60 }],
        outputs: [{ resource: "Cryston Plate", kind: "item", rate: 30 }] },
    ]],
  ["Gearing_Unit", "Gearing Unit", "Production II", [5, 5], 0,
    "A facility for processing gears.", [
      { inputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Ferrium Gear", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Amethyst Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Amethyst Gear", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Steel Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Steel Gear", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Cuprium Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cuprium Gear", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Cryston Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cryston Gear", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Hetonite Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Hetonite Gear", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Xiranite Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Xiranite Gear", kind: "item", rate: 30 }] },
    ]],
  ["Grinding_Unit", "Grinding Unit", "Production II", [5, 5], 0,
    "A facility for processing tubes.", [
      { inputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Ferrium Tube", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Amethyst Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Amethyst Tube", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Steel Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Steel Tube", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Cuprium Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cuprium Tube", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Cryston Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Cryston Tube", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Hetonite Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Hetonite Tube", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Xiranite Part", kind: "item", rate: 30 }],
        outputs: [{ resource: "Xiranite Tube", kind: "item", rate: 30 }] },
    ]],
  ["Packaging_Unit", "Packaging Unit", "Production II", [5, 5], 20,
    "A facility for packaging power components.", [
      { inputs: [{ resource: "Amethyst Part", kind: "item", rate: 30 }, { resource: "Aketine Powder", kind: "item", rate: 6 }],
        outputs: [{ resource: "Industrial Explosive", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Amethyst Part", kind: "item", rate: 30 }, { resource: "Originium Powder", kind: "item", rate: 60 }],
        outputs: [{ resource: "LC Valley Battery", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Ferrium Part", kind: "item", rate: 60 }, { resource: "Originium Powder", kind: "item", rate: 90 }],
        outputs: [{ resource: "SC Valley Battery", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Steel Part", kind: "item", rate: 60 }, { resource: "Dense Originium Powder", kind: "item", rate: 90 }],
        outputs: [{ resource: "HC Valley Battery", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }, { resource: "Ferrium Bottle (Yazhen Solution)", kind: "item", rate: 30 }],
        outputs: [{ resource: "Yazhen Syringe (C)", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Cuprium Part", kind: "item", rate: 30 }, { resource: "Cuprium Bottle (Yazhen Solution)", kind: "item", rate: 30 }],
        outputs: [{ resource: "Yazhen Syringe (A)", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }, { resource: "Ferrium Bottle (Jincao Solution)", kind: "item", rate: 30 }],
        outputs: [{ resource: "Jincao Drink", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Cuprium Part", kind: "item", rate: 30 }, { resource: "Cuprium Bottle (Jincao Solution)", kind: "item", rate: 30 }],
        outputs: [{ resource: "Jincao Tea", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Xiranite", kind: "item", rate: 30 }, { resource: "Dense Originium Powder", kind: "item", rate: 90 }],
        outputs: [{ resource: "LC Wuling Battery", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Xircon", kind: "item", rate: 30 }, { resource: "Dense Originium Powder", kind: "item", rate: 120 }],
        outputs: [{ resource: "SC Wuling Battery", kind: "item", rate: 6 }], time: 10 },
      { inputs: [{ resource: "Cuprium Canister", kind: "item", rate: 30 }, { resource: "Xiranite", kind: "item", rate: 30 }],
        outputs: [{ resource: "Separator Core", kind: "item", rate: 60 }], time: 2 },
    ]],
  ["Purification_Unit", "Purification Unit", "Production II", [5, 5], 0,
    "A facility for processing fluids.", [
      { inputs: [{ resource: "Sewage", kind: "fluid", rate: 30 }],
        outputs: [{ resource: "Clean Water", kind: "fluid", rate: 30 }] },
      { inputs: [{ resource: "Sewage", kind: "fluid", rate: 30 }],
        outputs: [{ resource: "Precipitation Acid", kind: "fluid", rate: 30 }] },
      { inputs: [{ resource: "Sewage", kind: "fluid", rate: 30 }],
        outputs: [{ resource: "Jincao Solution", kind: "fluid", rate: 30 }] },
      { inputs: [{ resource: "Sewage", kind: "fluid", rate: 30 }],
        outputs: [{ resource: "Yazhen Solution", kind: "fluid", rate: 30 }] },
      { inputs: [{ resource: "Sewage", kind: "fluid", rate: 30 }],
        outputs: [{ resource: "Cuprium Solution", kind: "fluid", rate: 30 }] },
      { inputs: [{ resource: "Sewage", kind: "fluid", rate: 30 }],
        outputs: [{ resource: "Hetonite Solution", kind: "fluid", rate: 30 }] },
    ]],
  ["Reactor_Crucible", "Reactor Crucible", "Production II", [5, 5], 0,
    "A facility for processing parts.", [
      { inputs: [{ resource: "Amethyst Part", kind: "item", rate: 30 }], outputs: [{ resource: "Amethyst Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }], outputs: [{ resource: "Ferrium Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Steel Part", kind: "item", rate: 30 }], outputs: [{ resource: "Steel Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Cuprium Part", kind: "item", rate: 30 }], outputs: [{ resource: "Cuprium Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Cryston Part", kind: "item", rate: 30 }], outputs: [{ resource: "Cryston Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Hetonite Part", kind: "item", rate: 30 }], outputs: [{ resource: "Hetonite Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Xiranite Part", kind: "item", rate: 30 }], outputs: [{ resource: "Xiranite Part", kind: "item", rate: 30 }] },
      { inputs: [{ resource: "Cryston Part", kind: "item", rate: 30 }], outputs: [{ resource: "Cryston Part", kind: "item", rate: 30 }] },
    ]],
  ["Separating_Unit", "Separating Unit", "Production II", [5, 5], 0,
    "A facility for separating fluids and gases from bottles/canisters.", []],
  ["Solid-Gas_Transmuting_Unit", "Solid-Gas Transmuting Unit", "Production II", [5, 5], 0,
    "A facility for transmuting solid items into gases.", []],
  ["Fluid-Gas_Transmuting_Unit", "Fluid-Gas Transmuting Unit", "Production II", [5, 5], 0,
    "A facility for transmuting fluids into gases.", []],

  // Power
  ["Electric_Pylon", "Electric Pylon", "Power", [5, 5], 0,
    "Power distribution infrastructure. No recipe.", []],
  ["Relay_Tower", "Relay Tower", "Power", [5, 5], 0,
    "Power distribution infrastructure. No recipe.", []],
  ["Thermal_Bank", "Thermal Bank", "Power", [5, 5], 0,
    "Generates power from various fuel items.", [
      { inputs: [{ resource: "Originium Ore", kind: "item", rate: 7.5 }],
        outputs: [{ resource: "Power", kind: "item", rate: 50 }], time: 8 },
      { inputs: [{ resource: "LC Valley Battery", kind: "item", rate: 1.5 }],
        outputs: [{ resource: "Power", kind: "item", rate: 220 }], time: 40 },
      { inputs: [{ resource: "SC Valley Battery", kind: "item", rate: 1.5 }],
        outputs: [{ resource: "Power", kind: "item", rate: 420 }], time: 40 },
      { inputs: [{ resource: "HC Valley Battery", kind: "item", rate: 1.5 }],
        outputs: [{ resource: "Power", kind: "item", rate: 1100 }], time: 40 },
      { inputs: [{ resource: "LC Wuling Battery", kind: "item", rate: 1.5 }],
        outputs: [{ resource: "Power", kind: "item", rate: 1600 }], time: 40 },
      { inputs: [{ resource: "SC Wuling Battery", kind: "item", rate: 1.5 }],
        outputs: [{ resource: "Power", kind: "item", rate: 2200 }], time: 40 },
    ]],
  ["Xiranite_Pylon", "Xiranite Pylon", "Power", [5, 5], 0,
    "Power distribution using Xiranite. No recipe.", []],
  ["Xiranite_Relay", "Xiranite Relay", "Power", [5, 5], 0,
    "Power distribution using Xiranite. No recipe.", []],

  // Resourcing — all miners extract at 30/min regardless of ore
  ["Electric_Mining_Rig", "Electric Mining Rig", "Resourcing", [5, 5], 5,
    "Mines Originium Ore and Amethyst Ore. Extracts at 30/min.", [
      { inputs: [], outputs: [{ resource: "Originium Ore", kind: "item", rate: 30 }] },
      { inputs: [], outputs: [{ resource: "Amethyst Ore", kind: "item", rate: 30 }] },
    ]],
  ["Electric_Mining_Rig_Mk_II", "Electric Mining Rig Mk II", "Resourcing", [5, 5], 0,
    "Upgraded Electric Mining Rig. Mines Cryston Ore and Ferrium Ore. Extracts at 30/min.", [
      { inputs: [], outputs: [{ resource: "Cryston Ore", kind: "item", rate: 30 }] },
      { inputs: [], outputs: [{ resource: "Ferrium Ore", kind: "item", rate: 30 }] },
    ]],
  ["Hydro_Mining_Rig", "Hydro Mining Rig", "Resourcing", [5, 5], 0,
    "Mines Cuprium-related resources. Extracts at 30/min.", [
      { inputs: [], outputs: [{ resource: "Cuprium Ore", kind: "item", rate: 30 }] },
    ]],
  ["Portable_Originium_Rig", "Portable Originium Rig", "Resourcing", [5, 5], 0,
    "Portable originium extraction. Extracts at 30/min.", [
      { inputs: [], outputs: [{ resource: "Originium Ore", kind: "item", rate: 30 }] },
    ]],
  ["Fluid_Pump", "Fluid Pump", "Resourcing", [5, 5], 0,
    "Extracts fluids. Recipe details should be added by the user.", []],
  ["Fluid_Supply_Unit", "Fluid Supply Unit", "Miscellaneous", [5, 5], 0,
    "Supplies fluids. Recipe details should be added by the user.", []],

  // Planting
  ["Aketine_Plot", "Aketine Plot", "Planting", [5, 5], 0,
    "Grows Aketine. Recipe details should be added by the user.", [
      { inputs: [{ resource: "Wood", kind: "item", rate: 30 }], outputs: [{ resource: "Aketine Seed", kind: "item", rate: 30 }] },
    ]],
  ["Amber_Rice_Plot", "Amber Rice Plot", "Planting", [5, 5], 0,
    "Grows Amber Rice. Recipe details should be added by the user.", []],
  ["Buckflower_Plot", "Buckflower Plot", "Planting", [5, 5], 0,
    "Grows Buckflower. Recipe details should be added by the user.", [
      { inputs: [{ resource: "Wood", kind: "item", rate: 30 }], outputs: [{ resource: "Buckflower Seed", kind: "item", rate: 30 }] },
    ]],
  ["Citrome_Plot", "Citrome Plot", "Planting", [5, 5], 0,
    "Grows Citrome. Recipe details should be added by the user.", [
      { inputs: [{ resource: "Wood", kind: "item", rate: 30 }], outputs: [{ resource: "Citrome Seed", kind: "item", rate: 30 }] },
    ]],
  ["Jincao_Plot", "Jincao Plot", "Planting", [5, 5], 0,
    "Grows Jincao. Recipe details should be added by the user.", [
      { inputs: [{ resource: "Jincao Seed", kind: "item", rate: 30 }], outputs: [{ resource: "Jincao", kind: "item", rate: 30 }] },
    ]],
  ["Redjade_Ginseng_Plot", "Redjade Ginseng Plot", "Planting", [5, 5], 0,
    "Grows Redjade Ginseng. Recipe details should be added by the user.", []],
  ["Reed_Rye_Plot", "Reed Rye Plot", "Planting", [5, 5], 0,
    "Grows Reed Rye. Recipe details should be added by the user.", []],
  ["Sandleaf_Plot", "Sandleaf Plot", "Planting", [5, 5], 0,
    "Grows Sandleaf. Recipe details should be added by the user.", [
      { inputs: [{ resource: "Sandleaf Seed", kind: "item", rate: 30 }], outputs: [{ resource: "Sandleaf", kind: "item", rate: 30 }] },
    ]],
  ["Tartpepper_Plot", "Tartpepper Plot", "Planting", [5, 5], 0,
    "Grows Tartpepper. Recipe details should be added by the user.", []],
  ["Yazhen_Plot", "Yazhen Plot", "Planting", [5, 5], 0,
    "Grows Yazhen. Recipe details should be added by the user.", [
      { inputs: [{ resource: "Yazhen Seed", kind: "item", rate: 30 }], outputs: [{ resource: "Yazhen", kind: "item", rate: 30 }] },
    ]],

  // Resourcing-gas
  ["Gas_Dispersing_Unit", "Gas Dispersing Unit", "Production II", [5, 5], 0,
    "Disperses gases. Recipe details should be added by the user.", []],
  ["Gas_Extractor", "Gas Extractor", "Resourcing", [5, 5], 0,
    "Extracts gases. Extracts at 30/min.", []],
  ["Gas_Reactor_Globe", "Gas Reactor Globe", "Production II", [5, 5], 0,
    "Reactor for gases. Recipe details should be added by the user.", []],
  ["Gas_Tank", "Gas Tank", "Depot Access", [5, 5], 0,
    "Stores gases. No recipe.", []],
];

const out = resolve("scraped/reports");
await mkdir(out, { recursive: true });

let written = 0;
for (const [slug, name, type, footprint, powerUse, description, recipes] of PAGES) {
  const data = {
    slug, name, type, footprint, powerUse, description,
    recipes: recipes.map((r, i) => ({
      id: `recipe_${i + 1}`,
      inputs: r.inputs || [],
      outputs: r.outputs || [],
      ...(r.time !== undefined ? { time: r.time } : {}),
    })),
  };
  await writeFile(resolve(out, `${slug}.json`), JSON.stringify(data, null, 2), "utf-8");
  written++;
}
console.log(`Wrote ${written} reports to ${out}`);
