// Generates src/data.ts from parsed/machines.json. The output is a
// TypeScript file that exports one constant per machine (named by
// uppercased identifier) plus an ALL_MACHINE_TYPES array. Hand-
// crafted placeholder machines for the test suite (MINER, FURNACE)
// are appended at the bottom of the generated file as a separate
// section — see src/data.ts.
//
// Run with: node generate-data.mjs
//
// Workflow: scrape.mjs → parse.mjs → generate-data.mjs

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const input = resolve("parsed/machines.json");
const output = resolve("src/data.ts");

const machines = JSON.parse(await readFile(input, "utf-8"));

const lines = [];
lines.push("// AUTO-GENERATED by generate-data.mjs from parsed/machines.json.");
lines.push("// Do not edit by hand — run `node generate-data.mjs` to refresh.");
lines.push("");
lines.push('import type { MachineType } from "./types.ts";');
lines.push("");

const isValidIdent = (s) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(s);

for (const m of machines) {
  const ident = m.name
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  if (!isValidIdent(ident)) {
    console.warn(`skipping ${m.name}: cannot make a valid identifier`);
    continue;
  }
  lines.push(`/** ${m.name} — ${m._meta.type} (${m.recipes.length} recipes) */`);
  lines.push(`export const ${ident}: MachineType = ${JSON.stringify({
    name: m.name,
    width: m.width,
    height: m.height,
    ports: m.ports,
    edgeBands: m.edgeBands,
    recipes: m.recipes,
  }, null, 2)};`);
  lines.push("");
}

lines.push("/** Every machine type known to the editor. */");
const idents = machines
  .map((m) => m.name.toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, ""))
  .filter(isValidIdent);
lines.push(`export const ALL_MACHINE_TYPES: MachineType[] = [`);
for (const id of idents) lines.push(`  ${id},`);
lines.push("];");

await writeFile(output, lines.join("\n"), "utf-8");
console.log(`Wrote ${idents.length} machines to ${output}`);
