// Generates src/data.ts from scraped/reports/*.json. Each report file
// is the manually-curated wiki data for one machine, with the recipe
// tables extracted by hand (not parsed by HTML regex). Run with:
//   node generate-data.mjs

import { readFile, readdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const input = resolve("scraped/reports");
const output = resolve("src/data.ts");

const files = (await readdir(input))
  .filter((f) => f.endsWith(".json"))
  .sort();
const machines = [];
for (const f of files) {
  const raw = await readFile(resolve(input, f), "utf-8");
  const data = JSON.parse(raw);
  machines.push({
    name: data.name,
    width: data.footprint?.[0] ?? 5,
    height: data.footprint?.[1] ?? 5,
    ports: [],
    edgeBands: {},
    recipes: (data.recipes ?? []).map((r, i) => ({
      id: r.id ?? `recipe_${i + 1}`,
      inputs: r.inputs ?? [],
      outputs: r.outputs ?? [],
      ...(r.time !== undefined ? { time: r.time } : {}),
    })),
  });
}

const isValidIdent = (s) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(s);

const lines = [];
lines.push("// AUTO-GENERATED by generate-data.mjs from scraped/reports/.");
lines.push("// The reports are hand-curated from the wiki. Re-curate the");
lines.push("// reports and re-run this script to refresh the data model.");
lines.push("");
lines.push('import type { MachineType } from "./types.ts";');
lines.push("");

const idents = [];
for (const m of machines) {
  const ident = m.name
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  if (!isValidIdent(ident)) {
    console.warn(`skipping ${m.name}: cannot make a valid identifier`);
    continue;
  }
  idents.push(ident);
  lines.push(`/** ${m.name} — ${m.recipes.length} recipes */`);
  lines.push(`export const ${ident}: MachineType = ${JSON.stringify(m, null, 2)};`);
  lines.push("");
}

lines.push("/** Every machine type known to the editor. */");
lines.push(`export const ALL_MACHINE_TYPES: MachineType[] = [`);
for (const id of idents) lines.push(`  ${id},`);
lines.push("];");

// ----------------------------------------------------------------------
// Hand-crafted placeholder machines for the test suite. The wiki
// doesn't have a separate "Miner" or "Furnace" page — these are the
// dev's simplified stand-ins.
// ----------------------------------------------------------------------

lines.push("");
lines.push("/** Miner: extracts raw ore from a node. Placeholder used by the test suite. */");
lines.push(`export const MINER: MachineType = {`);
lines.push(`  name: "Miner",`);
lines.push(`  width: 5,`);
lines.push(`  height: 5,`);
lines.push(`  ports: [],`);
lines.push(`  edgeBands: {`);
lines.push(`    north: { type: "output", resourceKind: "item" },`);
lines.push(`  },`);
lines.push(`  recipes: [],`);
lines.push(`};`);
lines.push("");
lines.push("/** Furnace: a 5x5 machine that takes an item on the south edge and outputs an item on the north edge. Placeholder used by the test suite. */");
lines.push(`export const FURNACE: MachineType = {`);
lines.push(`  name: "Furnace",`);
lines.push(`  width: 5,`);
lines.push(`  height: 5,`);
lines.push(`  ports: [`);
lines.push(`    {`);
lines.push(`      id: "water_input",`);
lines.push(`      type: "input",`);
lines.push(`      side: "west",`);
lines.push(`      tileIndex: 2,`);
lines.push(`      resource: "Water",`);
lines.push(`      kind: "fluid",`);
lines.push(`      rate: 10,`);
lines.push(`    },`);
lines.push(`  ],`);
lines.push(`  edgeBands: {`);
lines.push(`    south: { type: "input", resourceKind: "item" },`);
lines.push(`    north: { type: "output", resourceKind: "item" },`);
lines.push(`  },`);
lines.push(`  recipes: [`);
lines.push(`    {`);
lines.push(`      id: "iron_ore_to_iron_plate",`);
lines.push(`      inputs: [{ resource: "Iron Ore", kind: "item", rate: 30 }],`);
lines.push(`      outputs: [{ resource: "Iron Plate", kind: "item", rate: 15 }],`);
lines.push(`    },`);
lines.push(`  ],`);
lines.push(`};`);

await writeFile(output, lines.join("\n"), "utf-8");
console.log(`Wrote ${idents.length} machines to ${output}`);
